refresh_rate: 30 seconds
appenders:
  stdout:
    kind: console
    encoder:
      # https://docs.rs/log4rs/0.10.0/log4rs/encode/pattern/index.html
      pattern: "{P} - {M}:{L} {l} {m}\n"
  requests:
    kind: file
    path: "log/requests.log"
    encoder:
      pattern: "{d} - {m}{n}"
root:
  level: info
  appenders:
    - stdout
loggers:
  app::backend::db:
    level: info
  app::requests:
    level: info
    appenders:
      - requests
    additive: false

